Object.defineProperty(exports, "__esModule", { value: true });
exports.projectData = [
  {
    TaskID: 1,
    TaskName: "Project Initiation",
    StartDate: new Date("04/02/2020"),
    EndDate: new Date("04/10/2020"),
    status: "Completed",
    subtasks: [
      {
        TaskID: 2,
        TaskName: "Import Cleanup",
        Duration: 0.04,
        status: "Completed",
        status: "Completed",
        Progress: 1,
      },
      {
        TaskID: 3,
        TaskName: "Pre Processing DB backup",
        Duration: 0.04,
        Progress: 2,
        status: "Completed",
        Predeceesor: "2FS",
      },
      {
        TaskID: 4,
        TaskName: "Set APAC Batch Parameters",
        Duration: 0.04,
        Progress: 3,
        status: "Completed",
        Predeceesor: "3FS",
      },
      {
        TaskID: 5,
        TaskName: "Run APAC ANALYTIC clean",
        Duration: 0.1,
        Progress: 4,
        status: "In Progress",
        Predeceesor: "4FS",
      },

      {
        TaskID: 6,
        TaskName: "DGX Sec master delta...",
        Duration: 0.04,
        Progress: 4,
        status: "Completed",
        Predeceesor: "3FS",
      },

      {
        TaskID: 7,
        TaskName: "Monitoring Portia",
        Duration: 0.04,
        Progress: 4,
        status: "Completed",
        Predeceesor: "6FS",
      },

      {
        TaskID: 8,
        TaskName: "Soil test approval",
        StartDate: new Date("04/20/2020"),
        Duration: 0.04,
        Progress: 4,
        status: "Completed",
        Predeceesor: "7FS",
      },

      {
        TaskID: 9,
        TaskName: "Position...",
        StartDate: new Date("04/14/2020"),
        Duration: 0.04,
        Progress: 4,
        status: "Completed",
        Predeceesor: "8FS",
      },
      {
        TaskID: 10,
        TaskName: "ADCF Run",
        StartDate: new Date("04/14/2020"),
        Duration: 0.04,
        Progress: 4,
        status: "Completed",
        Predeceesor: "9FS",
      },
      {
        TaskID: 11,
        TaskName: "Batch Statements....",
        StartDate: new Date("04/14/2020"),
        Duration: 0.1,
        Progress: 6,
        status: "Completed",
        Predeceesor: "10FS",
      },
      {
        TaskID: 12,
        TaskName: "Position APAC ANALYSIS...",
        StartDate: new Date("04/14/2020"),
        Duration: 0.04,
        Progress: 4,
        status: "Completed",
        Predeceesor: "11FS",
      },
    ],
  },
];
